fullTextPath        = '/mnt/datasets/erudit/'
extractedTextPath   = 'fullText/'
rankingsPath        = 'rankings'
termsPath           = 'terms/'
picklePath          = 'pickles/'
SolrFilesPath       = 'solr.files/'
